name: Sync to Hugging Face hub

on:
  push:
    branches: [LEON]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Create models folder
        run: mkdir -p movie-recommendation-system/models

      - name: Debug - List files before TMDB check
        run: |
          ls -lR
      
      - name: Fail if TMDB file is present
        run: |
          if [ -f data/TMDB_movie_dataset_v11.csv ]; then
            echo "TMDB file detected! Aborting push."
            exit 1
          fi

      - name: Prepare files for Hugging Face push (exclude TMDB)
        run: |
            rsync -av --exclude='data/TMDB_movie_dataset_v11.csv' . output_dir/



      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git remote add hub https://SFG006:$HF_TOKEN@huggingface.co/spaces/SFG006/Illustrious-films LEON
             git push hub LEON --force
