name: Sync to Hugging Face hub

on:
  push:
    branches: [LEON]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false  # You don't need this now since LFS is removed

      - name: Create models folder
        run: mkdir -p movie-recommendation-system/models

      - name: Download movies.pkl from Google Drive
        run: |
          FILE_ID="1VI5hdOLksCINWPMa2Fv1hvHJqwJTGbdl"
          FILE_NAME="movies.pkl"
          wget --no-check-certificate "https://drive.google.com/uc?export=download&id=${FILE_ID}" -O movie-recommendation-system/models/${FILE_NAME}

      - name: Download vectors.pkl from Google Drive
        run: |
          FILE_ID="1YB8BSqYPS-Sce_9HpwugieHvXjHZwe5d"
          FILE_NAME="vectors.pkl"
          wget --no-check-certificate "https://drive.google.com/uc?export=download&id=${FILE_ID}" -O movie-recommendation-system/models/${FILE_NAME}

      - name: Download vectorizer.pkl from Google Drive
        run: |
          FILE_ID="1YB8BSqYPS-Sce_9HpwugieHvXjHZwe5d"
          FILE_NAME="vectorizer.pkl"
          wget --no-check-certificate "https://drive.google.com/uc?export=download&id=${FILE_ID}" -O movie-recommendation-system/models/${FILE_NAME}

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://SFG006:$HF_TOKEN@huggingface.co/spaces/SFG006/Illustrious-films main
